minimum_pre_commit_version: "4.0.0"
repos:
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.5.0
    hooks:
      - id: gdformat
        name: gdformat
      - id: gdlint
        name: gdlint
