@startuml
left to right direction
hide empty members
skinparam classAttributeIconSize 0
class "CanvasItem" as C_0 #59616d {
}
class "CanvasLayer" as C_1 #59616d {
}
class "Control" as C_2 #59616d {
}
class "MainLoop" as C_3 #59616d {
}
class "Node" as C_4 #59616d {
}
class "Node2D" as C_5 #59616d {
}
class "Node3D" as C_6 #59616d {
}
class "Object" as C_7 #59616d {
}
class "RefCounted" as C_8 #59616d {
}
class "Resource" as C_9 #59616d {
}
class "SceneTree" as C_10 #59616d {
}
class "Script" as C_11 #59616d {
}
class "ShowcaseCombatEntity" as C_12 #8f4f79 {
  +maximum_health
  +current_health
  +signal health_changed
  +signal defeated
  +receive_damage
  +is_alive
}
class "ShowcaseBaseActor" as C_13 #005a8d {
  +actor_label
  +weapon_profile
  +last_action
  +signal action_requested
  +request_action
  +attack_power
}
class "ShowcaseEnemyActor" as C_14 #005a8d {
  +aggression
  +weapon_profile_script
  +choose_action
  +create_default_profile
}
class "ShowcasePlayerActor" as C_15 #005a8d {
  +damage_service_script
  +request_primary_attack
  +preview_damage
}
class "ShowcaseBattleController" as C_16 #005a8d {
  +player_path
  +enemy_path
  +turn_index
  +signal battle_started
  +signal battle_finished
  +start_battle
  +finish_battle
}
class "ShowcaseWeaponProfile" as C_17 #005a8d {
  +display_name
  +base_damage
  +critical_multiplier
}
class "ShowcaseMainLoop" as C_18 #005a8d {
  +_initialize
}
class "ShowcaseDamageService" as C_19 #005a8d {
  +{static} calculate_damage
}
class "ShowcaseTargetingService" as C_20 #005a8d {
  +{static} choose_target
}
class "ShowcaseBattleHud" as C_21 #005a8d {
  +status_label_path
  +controller_script
  +controller_type_name
}
class "ShowcaseBattlePanel" as C_22 #005a8d {
  +headline
  +set_headline
}
class "ambient_marker" as C_23 #005a8d {
  +marker_radius
  +marker_position
}
class "ShowcaseArenaAnchor3D" as C_24 #005a8d {
  +anchor_id
  +world_transform
}
C_0 --|> C_4
C_1 --|> C_4
C_2 --|> C_0
C_3 --|> C_7
C_5 --|> C_0
C_6 --|> C_4
C_4 --|> C_7
C_8 --|> C_7
C_9 --|> C_8
C_10 --|> C_3
C_11 --|> C_9
C_12 --|> C_4
C_13 --|> C_12
C_14 --|> C_13
C_15 --|> C_13
C_16 --|> C_4
C_17 --|> C_9
C_18 --|> C_10
C_19 --|> C_8
C_20 --|> C_8
C_21 --|> C_1
C_22 --|> C_2
C_23 --|> C_5
C_24 --|> C_6
C_13::weapon_profile ..> C_17 : type
C_14::create_default_profile ..> C_9 : type
C_14::weapon_profile_script ..> C_11 : type
C_15::damage_service_script ..> C_11 : type
C_16::finish_battle ..> C_13 : type
C_16::"signal battle_finished" ..> C_13 : type
C_19::calculate_damage ..> C_17 : type
C_20::choose_target ..> C_13 : type
C_21::controller_script ..> C_11 : type
C_13::attack_power ..> C_19::calculate_damage : uses
C_14::weapon_profile_script ..> C_17 : uses
C_15::damage_service_script ..> C_19 : uses
C_21::controller_script ..> C_16 : uses
@enduml
